#
# PROGRAM:    assign1
# PROGRAMMER: Dominykas Karalius
# ZID:        Z1809478
# DATE:       09.04.2019
#

CCFLAGS = -Wall

Assign1: assign1.cc
	g++ $(CCFLAGS) assign1.cc -o Assign1

clean:
	- rm Assign1
