#
# PROGRAM:    assign3
# PROGRAMMER: Dominykas Karalius
# ZID:        Z1809478
# DATE:       09.26.2019
#

CCFLAGS = -Wall

Assign3: assign3.cc
	g++ $(CCFLAGS) assign3.cc -o Assign3

clean:
	- rm Assign3

