#
# PROGRAM:    assign2
# PROGRAMMER: Dominykas Karalius
# ZID:        Z1809478
# DATE:       09.16.2019
#

CCFLAGS = -Wall

Assign2: assign2.cc
	g++ $(CCFLAGS) assign2.cc -o Assign2

clean:
	- rm Assign2

