#
# PROGRAM:    Assign7
# PROGRAMMER: Dominykas Karalius
# ZID:        Z1809478
# DATE:       12.02.2019
#

CCFLAGS = -Wall

Assign6: assign7.cc
	g++ $(CCFLAGS) assign7.cc -o Assign7

clean:
	- rm Assign7

